### ISSUE TITLE
Using the 2x2 crafting grid in the player inventory causes IllegalClassLoadError crash

### ISSUE THREAD

**Issue by emberquill** [Tfarcenim/FastBenchMinusReplacement#2]
Trying to use the 2x2 player inventory crafting grid causes Minecraft to crash with an IllegalClassLoadError:

`org.spongepowered.asm.mixin.transformer.throwables.IllegalClassLoadError: Illegal classload request for accessor mixin tfar.fastbenchminusreplacement.mixin.PlayerContainerAccessor. The mixin is missing from fastbenchminusreplacement.mixins.json which owns package tfar.fastbenchminusreplacement.mixin.* and the mixin has not been applied.`

Full log file [here](https://pastebin.com/Mk80Etcm).

**Comment by Tfarcenim** [comment]
hmm, try redownloading, it seems like the jar might've corrupted

**Comment by emberquill** [comment]
[Same issue](https://pastebin.com/ZbjmgpFv) on a fresh instance with only forge, mixinbootstrap, and fastbench.
