### ISSUE TITLE
[1.16.1] No Crafting Output Shown Refined Storage

### ISSUE THREAD

**Issue by medtryx** [Tfarcenim/FastBenchMinusReplacement#3]
There is no crafting output visible in the crafting grid of Refined Storage. You are able to click in the output spot and pull out the result of crafting however. 

Recreated this issue with just: 

- forge-1.16.1-32.0.106-universal.jar
- refinedstorage-1.9.2.jar
- fastbenchminusreplacement-1.2a.jar

**Comment by Tfarcenim** [comment]
desync is fun
(Note to self: the issue is in the craftingresultslot and craftinginventory mixins, is there a way to filter out rs?)
