### ISSUE TITLE
[1.16.5] No crafting output shown on Engineer's Crafting Table from Immersive Engineering

### ISSUE THREAD

**Issue by Mooncat25** [Tfarcenim/FastBenchMinusReplacement#5]
Same situation as #3, the output is invisible, but you can still pick the items out. But different affected block, different mod versions.

### **Environment**
Minecraft 1.16.5
Forge 36.0.46
Immersive Engineering 1.16.5-4.2.2-132 ([Link](https://www.curseforge.com/minecraft/mc-mods/immersive-engineering))
FastWorkbench Minus Replacement 1.3

**Comment by Tfarcenim** [comment]
fixed in 1.4
